In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [3]:
os.chdir(r"C:\Users\박유경\Desktop\project")
#os.chdir(r"C:\Users\student\Desktop\20190118_Python 분석 기초\data")

In [13]:
# df = pd.read_csv('data_population.csv', header='infer',encoding='ISO-8859-1')
df = pd.read_csv('credit_card_data.csv', header='infer', na_values=[' '])
df

,pop_cd,year,month,avg_score,avg_rat,city,sex,ages,population,num_opencard,...,monthly_installments_loan,monthly_insurance_loan,monthly_sbk_loan,loan_commitment,inst_rep_loanb,ls_rep_loanb,credit_loan,mortgage_loan,credit_card_payment,credit_card_installments_payment
0,L011,2016,1,812,2,서울,NaN,10대,55000,1.44,...,0,0,0,1120000,8210000,78020000,92170000,87260000,0,0
1,L011,2016,2,773,4,서울,NaN,10대,380000,1.71,...,510000,220000,1020000,680000,4660000,23300000,8260000,42410000,4000,1000
2,L011,2016,3,771,4,서울,NaN,10대,387000,1.75,...,490000,210000,1140000,640000,4370000,22930000,8300000,41710000,3000,1000
3,L011,2016,4,770,4,서울,NaN,10대,412000,1.76,...,510000,240000,1340000,510000,4770000,22160000,9460000,41040000,4000,1000
4,L011,2016,5,771,4,서울,NaN,10대,414000,1.75,...,490000,340000,1490000,640000,4740000,21960000,9660000,40850000,3000,1000
5,L011,2016,6,771,4,서울,NaN,10대,410000,1.75,...,410000,320000,1630000,680000,4730000,21380000,9470000,40130000,4000,2000
6,L011,2016,7,772,4,서울,NaN,10대,407000,1.75,...,520000,320000,1670000,610000,4680000,20230000,8790000,38970000,4000,2000
7,L011,2016,8,772,4,서울,NaN,10대,403000,1.75,...,400000,140000,1720000,830000,4950000,20400000,9660000,40770000,4000,2000
8,L011,2016,9,772,4,서울,NaN,10대,399000,1.74,...,420000,210000,1850000,920000,5240000,20450000,10060000,41590000,5000,2000
9,L011,2016,10,773,4,서울,NaN,10대,395000,1.73,...,460000,190000,1930000,890000,5860000,20780000,9720000,43070000,4000,2000
10,L011,2016,11,775,4,서울,NaN,10대,390000,1.71,...,560000,120000,2040000,880000,5740000,21150000,9440000,43600000,4000,2000
11,L011,2016,12,775,4,서울,NaN,10대,387000,1.71,...,810000,340000,1960000,930000,5290000,20590000,10040000,40750000,4000,2000
12,L011,2017,1,776,4,서울,NaN,10대,386000,1.69,...,770000,340000,1850000,1010000,5320000,20360000,10150000,40510000,5000,2000
13,L011,2017,2,774,4,서울,NaN,10대,355000,1.75,...,770000,250000,2050000,1040000,5850000,19730000,10220000,41130000,5000,2000
14,L011,2017,3,772,4,서울,NaN,10대,360000,1.78,...,780000,270000,2160000,940000,6420000,20460000,10430000,43390000,5000,2000
15,L011,2017,4,772,4,서울,NaN,10대,378000,1.79,...,710000,280000,2110000,980000,6910000,19280000,10890000,42370000,5000,2000
16,L011,2017,5,773,4,서울,NaN,10대,379000,1.79,...,590000,310000,2120000,970000,6030000,18920000,10140000,41170000,5000,2000
17,L011,2017,6,773,4,서울,NaN,10대,375000,1.79,...,630000,90000,2120000,990000,5790000,26320000,10010000,55070000,5000,2000
18,L011,2017,7,774,4,서울,NaN,10대,371000,1.79,...,650000,300000,2210000,1070000,5960000,27200000,10360000,56640000,5000,2000
19,L011,2017,8,774,4,서울,NaN,10대,368000,1.79,...,550000,200000,1710000,950000,5180000,22410000,10510000,40250000,5000,2000
20,L011,2017,9,774,4,서울,NaN,10대,366000,1.78,...,610000,370000,1670000,760000,5390000,20060000,10530000,36400000,6000,2000
21,L011,2017,10,775,4,서울,NaN,10대,362000,1.77,...,600000,250000,1820000,830000,5390000,20720000,10520000,38640000,5000,2000
22,L011,2017,11,776,4,서울,NaN,10대,355000,1.76,...,630000,80000,1810000,830000,5170000,22590000,10050000,42270000,5000,2000
23,L011,2017,12,777,4,서울,NaN,10대,352000,1.76,...,650000,80000,1670000,790000,5180000,23470000,9640000,44760000,5000,2000
24,L021,2016,1,811,2,인천,NaN,10대,17000,1.29,...,130000,0,0,0,130000,4840000,0,4970000,0,0
25,L021,2016,2,767,4,인천,NaN,10대,102000,1.65,...,1810000,800000,1300000,150000,8620000,5160000,6810000,18610000,4000,2000
26,L021,2016,3,765,4,인천,NaN,10대,104000,1.68,...,1980000,820000,1510000,140000,8150000,5080000,7140000,17930000,4000,2000
27,L021,2016,4,764,4,인천,NaN,10대,108000,1.72,...,2150000,980000,1610000,180000,8630000,5400000,7540000,19280000,5000,2000
28,L021,2016,5,765,4,인천,NaN,10대,109000,1.72,...,2140000,760000,1800000,130000,8770000,5230000,8000000,19220000,5000,2000
29,L021,2016,6,765,4,인천,NaN,10대,108000,1.72,...,2010000,530000,1930000,120000,6830000,5850000,7670000,17590000,5000,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3858,Y90,2017,7,827,3,NaN,남자,90대,195000,0.12,...,540000,370000,170000,14030000,16590000,56800000,21390000,103890000,98000,20000
3859,Y90,2017,8,827,3,NaN,남자,90대,197000,0.12,...,540000,410000,190000,13750000,16190000,55350000,20830000,101350000,104000,23000
3860,Y90,2017,9,827,3,NaN,남자,90대,200000,0.12,...,580000,340000,190000,13850000,16910000,54510000,21410000,101020000,104000,23000
3861,Y90,2017,10,827,3,NaN,남자,90대,203000,0.12,...,630000,360000,180000,14280000,16770000,54710000,20940000,101800000,112000,27000
3862,Y90,2017,11,828,3,NaN,남자,90대,208000,0.12,...,620000,360000,230000,17480000,16520000,55150000,21440000,105770000,106000,26000
3863,Y90,2017,12,828,3,NaN,남자,90대,230000,0.11,...,610000,360000,210000,17470000,16840000,55540000,21820000,106110000,99000,22000
3864,Y95,2016,1,768,3,NaN,여자,90대,132000,1.17,...,170000,870000,90000,7430000,21260000,54820000,28820000,97020000,42000,14000
3865,Y95,2016,2,815,3,NaN,여자,90대,174000,0.09,...,230000,740000,150000,6740000,22780000,53440000,30800000,96460000,28000,9000
3866,Y95,2016,3,815,3,NaN,여자,90대,177000,0.10,...,80000,680000,140000,7010000,22040000,53290000,30910000,95540000,26000,8000
3867,Y95,2016,4,815,3,NaN,여자,90대,180000,0.10,...,70000,660000,140000,7070000,22150000,53540000,30160000,96060000,31000,8000
3868,Y95,2016,5,815,3,NaN,여자,90대,184000,0.10,...,70000,670000,140000,7030000,22100000,53970000,30690000,96130000,30000,8000
3869,Y95,2016,6,815,3,NaN,여자,90대,192000,0.09,...,70000,750000,20000,7190000,22160000,56820000,33740000,99370000,30000,8000
3870,Y95,2016,7,816,3,NaN,여자,90대,194000,0.09,...,70000,740000,30000,7010000,22240000,57590000,31710000,100250000,30000,10000
3871,Y95,2016,8,816,3,NaN,여자,90대,196000,0.09,...,60000,680000,160000,7200000,22420000,58850000,31180000,101640000,33000,9000
3872,Y95,2016,9,816,3,NaN,여자,90대,200000,0.09,...,60000,710000,140000,6990000,22310000,58190000,30470000,100840000,33000,9000
3873,Y95,2016,10,817,3,NaN,여자,90대,203000,0.10,...,60000,720000,140000,6960000,22280000,58340000,31840000,100920000,37000,10000
3874,Y95,2016,11,817,3,NaN,여자,90대,206000,0.10,...,60000,810000,170000,6860000,22460000,59270000,30110000,101670000,33000,10000
3875,Y95,2016,12,817,3,NaN,여자,90대,208000,0.10,...,50000,820000,330000,6640000,22310000,58150000,30020000,99580000,31000,8000
3876,Y95,2017,1,818,3,NaN,여자,90대,212000,0.10,...,50000,920000,320000,7280000,21920000,57260000,29710000,98970000,33000,9000
3877,Y95,2017,2,818,3,NaN,여자,90대,209000,0.10,...,50000,750000,310000,7050000,21950000,57500000,29060000,98920000,31000,7000
3878,Y95,2017,3,818,3,NaN,여자,90대,213000,0.11,...,40000,800000,300000,7100000,21710000,57910000,30700000,99240000,31000,8000
3879,Y95,2017,4,818,3,NaN,여자,90대,218000,0.11,...,60000,770000,440000,7280000,21510000,58630000,28760000,99980000,35000,10000
3880,Y95,2017,5,818,3,NaN,여자,90대,222000,0.11,...,50000,800000,510000,7240000,21560000,57930000,28290000,99020000,36000,9000
3881,Y95,2017,6,819,3,NaN,여자,90대,226000,0.11,...,50000,830000,500000,7280000,21450000,57400000,27830000,98150000,36000,8000
3882,Y95,2017,7,819,3,NaN,여자,90대,229000,0.11,...,40000,800000,300000,7210000,21160000,57030000,27260000,97300000,41000,10000
3883,Y95,2017,8,819,3,NaN,여자,90대,232000,0.11,...,40000,840000,450000,7290000,21340000,57900000,26130000,98590000,36000,11000
3884,Y95,2017,9,819,3,NaN,여자,90대,235000,0.11,...,400000,840000,430000,7110000,21710000,57910000,30360000,99110000,36000,8000
3885,Y95,2017,10,819,3,NaN,여자,90대,239000,0.11,...,1190000,790000,450000,6950000,21720000,57370000,32470000,98340000,36000,12000
3886,Y95,2017,11,819,3,NaN,여자,90대,243000,0.11,...,1230000,860000,580000,6850000,21700000,57300000,33480000,97520000,32000,11000
3887,Y95,2017,12,820,3,NaN,여자,90대,265000,0.11,...,1180000,930000,470000,6480000,21260000,58840000,32800000,98500000,35000,10000

In [7]:
df.shape

(3888, 26)

In [10]:
df_s=df[(df.sex =='남자') | (df.sex=='여자')]
df_s

,pop_cd,year,month,avg_score,avg_rat,city,sex,ages,population,num_opencard,...,monthly_installments_loan,monthly_insurance_loan,monthly_sbk_loan,loan_commitment,inst_rep_loanb,ls_rep_loanb,credit_loan,mortgage_loan,credit_card_payment,credit_card_installments_payment
384,Y10,2016,1,811,2,NaN,남자,10대,960000,1.16,...,40000,0,0,940000,2310000,45440000,16760000,49540000,0,0
385,Y10,2016,2,767,4,NaN,남자,10대,1144000,1.59,...,1470000,400000,300000,1160000,5560000,9340000,7830000,19930000,2000,1000
386,Y10,2016,3,765,4,NaN,남자,10대,1168000,1.62,...,1490000,470000,260000,1100000,5860000,9160000,7750000,20090000,2000,1000
387,Y10,2016,4,764,4,NaN,남자,10대,1211000,1.66,...,1520000,670000,220000,1070000,6250000,9260000,8310000,20620000,2000,1000
388,Y10,2016,5,765,4,NaN,남자,10대,1216000,1.66,...,1650000,690000,220000,580000,6360000,9140000,8630000,19660000,2000,1000
389,Y10,2016,6,765,4,NaN,남자,10대,1209000,1.67,...,1510000,590000,260000,610000,6310000,9080000,8650000,19650000,3000,1000
390,Y10,2016,7,766,4,NaN,남자,10대,1203000,1.67,...,1520000,530000,300000,640000,6200000,8790000,8640000,19240000,2000,1000
391,Y10,2016,8,766,4,NaN,남자,10대,1198000,1.67,...,1490000,480000,290000,610000,6560000,9110000,8520000,20330000,3000,1000
392,Y10,2016,9,766,4,NaN,남자,10대,1192000,1.67,...,1540000,530000,280000,600000,6790000,9550000,8540000,21330000,3000,1000
393,Y10,2016,10,767,4,NaN,남자,10대,1182000,1.65,...,1580000,520000,320000,630000,7020000,9730000,8650000,21900000,3000,1000
394,Y10,2016,11,768,4,NaN,남자,10대,1170000,1.64,...,1590000,350000,320000,600000,6770000,10320000,9080000,22120000,3000,1000
395,Y10,2016,12,769,4,NaN,남자,10대,1174000,1.61,...,1600000,500000,310000,670000,6400000,10350000,9050000,22160000,3000,1000
396,Y10,2017,1,770,4,NaN,남자,10대,1182000,1.58,...,1600000,510000,310000,670000,6290000,9890000,8790000,21770000,3000,1000
397,Y10,2017,2,769,4,NaN,남자,10대,1190000,1.56,...,1590000,480000,360000,620000,6670000,11960000,8840000,25920000,3000,1000
398,Y10,2017,3,767,4,NaN,남자,10대,1205000,1.58,...,1670000,510000,370000,600000,6860000,12320000,9030000,26960000,3000,1000
399,Y10,2017,4,767,4,NaN,남자,10대,1243000,1.62,...,1700000,520000,360000,580000,7390000,9410000,9490000,23010000,3000,1000
400,Y10,2017,5,768,4,NaN,남자,10대,1242000,1.62,...,1890000,550000,360000,600000,7480000,9580000,9450000,23640000,3000,1000
401,Y10,2017,6,769,4,NaN,남자,10대,1234000,1.62,...,1910000,440000,370000,650000,7420000,9380000,9500000,23370000,3000,1000
402,Y10,2017,7,769,4,NaN,남자,10대,1227000,1.63,...,1880000,380000,350000,580000,7740000,9370000,9670000,23830000,3000,1000
403,Y10,2017,8,769,4,NaN,남자,10대,1223000,1.62,...,1360000,250000,270000,560000,5210000,6630000,9450000,13940000,3000,1000
404,Y10,2017,9,769,4,NaN,남자,10대,1218000,1.63,...,1370000,280000,290000,550000,5270000,5890000,9400000,12920000,3000,1000
405,Y10,2017,10,770,4,NaN,남자,10대,1208000,1.61,...,1560000,240000,290000,530000,5290000,6030000,9290000,13130000,3000,1000
406,Y10,2017,11,771,4,NaN,남자,10대,1198000,1.60,...,1730000,250000,320000,540000,5650000,6390000,9200000,14440000,3000,1000
407,Y10,2017,12,772,4,NaN,남자,10대,1203000,1.58,...,1950000,320000,280000,500000,5960000,6000000,9060000,14460000,3000,1000
408,Y15,2016,1,813,2,NaN,여자,10대,921000,1.20,...,260000,0,0,820000,4260000,26910000,21900000,33030000,0,0
409,Y15,2016,2,771,4,NaN,여자,10대,1084000,1.49,...,1050000,180000,2240000,680000,4890000,8550000,7880000,22650000,4000,2000
410,Y15,2016,3,769,4,NaN,여자,10대,1108000,1.53,...,1160000,200000,2440000,610000,4760000,8720000,7910000,22810000,3000,1000
411,Y15,2016,4,768,4,NaN,여자,10대,1142000,1.57,...,1230000,220000,2690000,600000,4720000,9010000,8330000,23210000,4000,2000
412,Y15,2016,5,768,4,NaN,여자,10대,1143000,1.58,...,1210000,320000,2930000,590000,4880000,9140000,8440000,24010000,4000,2000
413,Y15,2016,6,769,4,NaN,여자,10대,1135000,1.58,...,1180000,350000,3110000,550000,4680000,9030000,8550000,23180000,4000,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3858,Y90,2017,7,827,3,NaN,남자,90대,195000,0.12,...,540000,370000,170000,14030000,16590000,56800000,21390000,103890000,98000,20000
3859,Y90,2017,8,827,3,NaN,남자,90대,197000,0.12,...,540000,410000,190000,13750000,16190000,55350000,20830000,101350000,104000,23000
3860,Y90,2017,9,827,3,NaN,남자,90대,200000,0.12,...,580000,340000,190000,13850000,16910000,54510000,21410000,101020000,104000,23000
3861,Y90,2017,10,827,3,NaN,남자,90대,203000,0.12,...,630000,360000,180000,14280000,16770000,54710000,20940000,101800000,112000,27000
3862,Y90,2017,11,828,3,NaN,남자,90대,208000,0.12,...,620000,360000,230000,17480000,16520000,55150000,21440000,105770000,106000,26000
3863,Y90,2017,12,828,3,NaN,남자,90대,230000,0.11,...,610000,360000,210000,17470000,16840000,55540000,21820000,106110000,99000,22000
3864,Y95,2016,1,768,3,NaN,여자,90대,132000,1.17,...,170000,870000,90000,7430000,21260000,54820000,28820000,97020000,42000,14000
3865,Y95,2016,2,815,3,NaN,여자,90대,174000,0.09,...,230000,740000,150000,6740000,22780000,53440000,30800000,96460000,28000,9000
3866,Y95,2016,3,815,3,NaN,여자,90대,177000,0.10,...,80000,680000,140000,7010000,22040000,53290000,30910000,95540000,26000,8000
3867,Y95,2016,4,815,3,NaN,여자,90대,180000,0.10,...,70000,660000,140000,7070000,22150000,53540000,30160000,96060000,31000,8000
3868,Y95,2016,5,815,3,NaN,여자,90대,184000,0.10,...,70000,670000,140000,7030000,22100000,53970000,30690000,96130000,30000,8000
3869,Y95,2016,6,815,3,NaN,여자,90대,192000,0.09,...,70000,750000,20000,7190000,22160000,56820000,33740000,99370000,30000,8000
3870,Y95,2016,7,816,3,NaN,여자,90대,194000,0.09,...,70000,740000,30000,7010000,22240000,57590000,31710000,100250000,30000,10000
3871,Y95,2016,8,816,3,NaN,여자,90대,196000,0.09,...,60000,680000,160000,7200000,22420000,58850000,31180000,101640000,33000,9000
3872,Y95,2016,9,816,3,NaN,여자,90대,200000,0.09,...,60000,710000,140000,6990000,22310000,58190000,30470000,100840000,33000,9000
3873,Y95,2016,10,817,3,NaN,여자,90대,203000,0.10,...,60000,720000,140000,6960000,22280000,58340000,31840000,100920000,37000,10000
3874,Y95,2016,11,817,3,NaN,여자,90대,206000,0.10,...,60000,810000,170000,6860000,22460000,59270000,30110000,101670000,33000,10000
3875,Y95,2016,12,817,3,NaN,여자,90대,208000,0.10,...,50000,820000,330000,6640000,22310000,58150000,30020000,99580000,31000,8000
3876,Y95,2017,1,818,3,NaN,여자,90대,212000,0.10,...,50000,920000,320000,7280000,21920000,57260000,29710000,98970000,33000,9000
3877,Y95,2017,2,818,3,NaN,여자,90대,209000,0.10,...,50000,750000,310000,7050000,21950000,57500000,29060000,98920000,31000,7000
3878,Y95,2017,3,818,3,NaN,여자,90대,213000,0.11,...,40000,800000,300000,7100000,21710000,57910000,30700000,99240000,31000,8000
3879,Y95,2017,4,818,3,NaN,여자,90대,218000,0.11,...,60000,770000,440000,7280000,21510000,58630000,28760000,99980000,35000,10000
3880,Y95,2017,5,818,3,NaN,여자,90대,222000,0.11,...,50000,800000,510000,7240000,21560000,57930000,28290000,99020000,36000,9000
3881,Y95,2017,6,819,3,NaN,여자,90대,226000,0.11,...,50000,830000,500000,7280000,21450000,57400000,27830000,98150000,36000,8000
3882,Y95,2017,7,819,3,NaN,여자,90대,229000,0.11,...,40000,800000,300000,7210000,21160000,57030000,27260000,97300000,41000,10000
3883,Y95,2017,8,819,3,NaN,여자,90대,232000,0.11,...,40000,840000,450000,7290000,21340000,57900000,26130000,98590000,36000,11000
3884,Y95,2017,9,819,3,NaN,여자,90대,235000,0.11,...,400000,840000,430000,7110000,21710000,57910000,30360000,99110000,36000,8000
3885,Y95,2017,10,819,3,NaN,여자,90대,239000,0.11,...,1190000,790000,450000,6950000,21720000,57370000,32470000,98340000,36000,12000
3886,Y95,2017,11,819,3,NaN,여자,90대,243000,0.11,...,1230000,860000,580000,6850000,21700000,57300000,33480000,97520000,32000,11000
3887,Y95,2017,12,820,3,NaN,여자,90대,265000,0.11,...,1180000,930000,470000,6480000,21260000,58840000,32800000,98500000,35000,10000

In [12]:
df_r=df[-((df.sex=='남자') | (df.sex=='여자'))]
df_r

,pop_cd,year,month,avg_score,avg_rat,city,sex,ages,population,num_opencard,...,monthly_installments_loan,monthly_insurance_loan,monthly_sbk_loan,loan_commitment,inst_rep_loanb,ls_rep_loanb,credit_loan,mortgage_loan,credit_card_payment,credit_card_installments_payment
0,L011,2016,1,812,2,서울,NaN,10대,55000,1.44,...,0,0,0,1120000,8210000,78020000,92170000,87260000,0,0
1,L011,2016,2,773,4,서울,NaN,10대,380000,1.71,...,510000,220000,1020000,680000,4660000,23300000,8260000,42410000,4000,1000
2,L011,2016,3,771,4,서울,NaN,10대,387000,1.75,...,490000,210000,1140000,640000,4370000,22930000,8300000,41710000,3000,1000
3,L011,2016,4,770,4,서울,NaN,10대,412000,1.76,...,510000,240000,1340000,510000,4770000,22160000,9460000,41040000,4000,1000
4,L011,2016,5,771,4,서울,NaN,10대,414000,1.75,...,490000,340000,1490000,640000,4740000,21960000,9660000,40850000,3000,1000
5,L011,2016,6,771,4,서울,NaN,10대,410000,1.75,...,410000,320000,1630000,680000,4730000,21380000,9470000,40130000,4000,2000
6,L011,2016,7,772,4,서울,NaN,10대,407000,1.75,...,520000,320000,1670000,610000,4680000,20230000,8790000,38970000,4000,2000
7,L011,2016,8,772,4,서울,NaN,10대,403000,1.75,...,400000,140000,1720000,830000,4950000,20400000,9660000,40770000,4000,2000
8,L011,2016,9,772,4,서울,NaN,10대,399000,1.74,...,420000,210000,1850000,920000,5240000,20450000,10060000,41590000,5000,2000
9,L011,2016,10,773,4,서울,NaN,10대,395000,1.73,...,460000,190000,1930000,890000,5860000,20780000,9720000,43070000,4000,2000
10,L011,2016,11,775,4,서울,NaN,10대,390000,1.71,...,560000,120000,2040000,880000,5740000,21150000,9440000,43600000,4000,2000
11,L011,2016,12,775,4,서울,NaN,10대,387000,1.71,...,810000,340000,1960000,930000,5290000,20590000,10040000,40750000,4000,2000
12,L011,2017,1,776,4,서울,NaN,10대,386000,1.69,...,770000,340000,1850000,1010000,5320000,20360000,10150000,40510000,5000,2000
13,L011,2017,2,774,4,서울,NaN,10대,355000,1.75,...,770000,250000,2050000,1040000,5850000,19730000,10220000,41130000,5000,2000
14,L011,2017,3,772,4,서울,NaN,10대,360000,1.78,...,780000,270000,2160000,940000,6420000,20460000,10430000,43390000,5000,2000
15,L011,2017,4,772,4,서울,NaN,10대,378000,1.79,...,710000,280000,2110000,980000,6910000,19280000,10890000,42370000,5000,2000
16,L011,2017,5,773,4,서울,NaN,10대,379000,1.79,...,590000,310000,2120000,970000,6030000,18920000,10140000,41170000,5000,2000
17,L011,2017,6,773,4,서울,NaN,10대,375000,1.79,...,630000,90000,2120000,990000,5790000,26320000,10010000,55070000,5000,2000
18,L011,2017,7,774,4,서울,NaN,10대,371000,1.79,...,650000,300000,2210000,1070000,5960000,27200000,10360000,56640000,5000,2000
19,L011,2017,8,774,4,서울,NaN,10대,368000,1.79,...,550000,200000,1710000,950000,5180000,22410000,10510000,40250000,5000,2000
20,L011,2017,9,774,4,서울,NaN,10대,366000,1.78,...,610000,370000,1670000,760000,5390000,20060000,10530000,36400000,6000,2000
21,L011,2017,10,775,4,서울,NaN,10대,362000,1.77,...,600000,250000,1820000,830000,5390000,20720000,10520000,38640000,5000,2000
22,L011,2017,11,776,4,서울,NaN,10대,355000,1.76,...,630000,80000,1810000,830000,5170000,22590000,10050000,42270000,5000,2000
23,L011,2017,12,777,4,서울,NaN,10대,352000,1.76,...,650000,80000,1670000,790000,5180000,23470000,9640000,44760000,5000,2000
24,L021,2016,1,811,2,인천,NaN,10대,17000,1.29,...,130000,0,0,0,130000,4840000,0,4970000,0,0
25,L021,2016,2,767,4,인천,NaN,10대,102000,1.65,...,1810000,800000,1300000,150000,8620000,5160000,6810000,18610000,4000,2000
26,L021,2016,3,765,4,인천,NaN,10대,104000,1.68,...,1980000,820000,1510000,140000,8150000,5080000,7140000,17930000,4000,2000
27,L021,2016,4,764,4,인천,NaN,10대,108000,1.72,...,2150000,980000,1610000,180000,8630000,5400000,7540000,19280000,5000,2000
28,L021,2016,5,765,4,인천,NaN,10대,109000,1.72,...,2140000,760000,1800000,130000,8770000,5230000,8000000,19220000,5000,2000
29,L021,2016,6,765,4,인천,NaN,10대,108000,1.72,...,2010000,530000,1930000,120000,6830000,5850000,7670000,17590000,5000,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3810,L159,2017,7,816,3,경남,NaN,90대,10000,0.25,...,0,0,260000,4560000,8070000,26780000,7830000,47310000,16000,5000
3811,L159,2017,8,817,3,경남,NaN,90대,11000,0.25,...,0,0,250000,4380000,7750000,28210000,7860000,47990000,15000,6000
3812,L159,2017,9,817,3,경남,NaN,90대,11000,0.25,...,0,0,250000,4210000,9310000,27660000,7840000,48570000,14000,6000
3813,L159,2017,10,817,3,경남,NaN,90대,11000,0.25,...,560000,0,240000,4150000,9630000,27040000,10680000,47230000,14000,6000
3814,L159,2017,11,817,3,경남,NaN,90대,11000,0.26,...,550000,190000,240000,3870000,9480000,27540000,12320000,46940000,12000,6000
3815,L159,2017,12,819,3,경남,NaN,90대,12000,0.26,...,560000,650000,320000,3610000,9480000,27870000,12270000,46570000,11000,5000
3816,L169,2016,1,767,3,제주,NaN,90대,2000,1.12,...,0,290000,0,2110000,5330000,32360000,10680000,54920000,16000,9000
3817,L169,2016,2,812,3,제주,NaN,90대,2000,0.21,...,0,0,0,2400000,6110000,34910000,12710000,51820000,8000,5000
3818,L169,2016,3,812,3,제주,NaN,90대,2000,0.21,...,0,0,0,2540000,6130000,34560000,12570000,53620000,7000,8000
3819,L169,2016,4,812,3,제주,NaN,90대,2000,0.21,...,0,0,0,2710000,6190000,34950000,12290000,55840000,192000,9000
3820,L169,2016,5,813,3,제주,NaN,90대,2000,0.21,...,0,0,0,2620000,6490000,33180000,13150000,51940000,10000,9000
3821,L169,2016,6,814,3,제주,NaN,90대,2000,0.21,...,0,0,0,2620000,6470000,32110000,13460000,51650000,11000,10000
3822,L169,2016,7,814,3,제주,NaN,90대,2000,0.20,...,0,0,0,2910000,6820000,31550000,13730000,52230000,9000,6000
3823,L169,2016,8,816,3,제주,NaN,90대,2000,0.21,...,0,0,0,2900000,6780000,31350000,14000000,51920000,12000,5000
3824,L169,2016,9,816,3,제주,NaN,90대,2000,0.21,...,0,0,0,2600000,6680000,32060000,15180000,52570000,10000,9000
3825,L169,2016,10,817,3,제주,NaN,90대,2000,0.21,...,0,0,0,2640000,7050000,32600000,15260000,53340000,11000,6000
3826,L169,2016,11,818,3,제주,NaN,90대,2000,0.21,...,0,0,0,2680000,7670000,26890000,15340000,45350000,12000,19000
3827,L169,2016,12,817,3,제주,NaN,90대,2000,0.21,...,0,0,0,1960000,7840000,18990000,15250000,33560000,10000,8000
3828,L169,2017,1,818,3,제주,NaN,90대,3000,0.22,...,0,0,0,2000000,7760000,19410000,24470000,30550000,16000,14000
3829,L169,2017,2,813,3,제주,NaN,90대,2000,0.30,...,0,0,0,2150000,7780000,14190000,17490000,26670000,18000,8000
3830,L169,2017,3,814,3,제주,NaN,90대,2000,0.31,...,0,0,0,3080000,7480000,13740000,17090000,27450000,16000,16000
3831,L169,2017,4,813,3,제주,NaN,90대,2000,0.31,...,0,0,0,2830000,7310000,13370000,16490000,28050000,12000,5000
3832,L169,2017,5,814,3,제주,NaN,90대,2000,0.32,...,0,0,0,2880000,7360000,12950000,15350000,27980000,12000,6000
3833,L169,2017,6,814,3,제주,NaN,90대,2000,0.32,...,0,0,0,2880000,7310000,16610000,16300000,31740000,14000,10000
3834,L169,2017,7,814,3,제주,NaN,90대,2000,0.32,...,0,0,0,2830000,6680000,18140000,17060000,32850000,14000,8000
3835,L169,2017,8,810,3,제주,NaN,90대,2000,0.38,...,0,0,0,3000000,6990000,18960000,17060000,35400000,15000,7000
3836,L169,2017,9,809,3,제주,NaN,90대,2000,0.41,...,0,0,0,2830000,7640000,18970000,17940000,34670000,18000,1000
3837,L169,2017,10,809,3,제주,NaN,90대,2000,0.42,...,0,0,0,2940000,7910000,16000000,17940000,30240000,13000,8000
3838,L169,2017,11,810,3,제주,NaN,90대,2000,0.43,...,0,0,0,2780000,7420000,31050000,17560000,51510000,15000,7000
3839,L169,2017,12,811,3,제주,NaN,90대,2000,0.43,...,0,0,0,2830000,7320000,31270000,17040000,52120000,15000,12000

In [26]:
print(df_r[df_r['avg_rat'].isin(['8'])])

Empty DataFrame
Columns: [pop_cd, year, month, avg_score, avg_rat, city, sex, ages, population, num_opencard, num_usecard, monthly_card_spend, monthly_lc, monthly_loan, monthly_bk_loan, monthly_cd_loan, monthly_installments_loan, monthly_insurance_loan, monthly_sbk_loan, loan_commitment, inst_rep_loanb, ls_rep_loanb, credit_loan, mortgage_loan, credit_card_payment, credit_card_installments_payment]
Index: []

[0 rows x 26 columns]

In [29]:
opencard_age=df_r['num_opencard'].groupby(df_r['ages']) #연령별 개설 카드수

In [30]:
opencard_age.mean()

ages
10대    1.706484
20대    3.676615
30대    4.249193
40대    3.840781
50대    3.144297
60대    2.253021
70대    1.303542
80대    0.672344
90대    0.273750
Name: num_opencard, dtype: float64

In [31]:
usecard_age=df_r['num_usecard'].groupby(df_r['ages']) #연령별 이용 카드 수

In [32]:
usecard_age.mean()

ages
10대    1.051615
20대    1.789740
30대    2.224141
40대    2.190651
50대    1.839219
60대    1.328620
70대    0.727630
80대    0.314479
90대    0.109922
Name: num_usecard, dtype: float64

In [43]:
# 연령별 개설 카드 수 이용 카드 수 비교
import matplotlib.pyplot as plt
import matplotlib
import matplotlib.font_manager as fm
import pyecharts

font_location = 'c:/Windows/Fonts/malgun.ttf'
font_name = fm.FontProperties(fname = font_location).get_name()
matplotlib.rc('font', family = font_name)

# x=df_r['ages']
# y1=df_r['num_opencard']
# y2=df_r['num_usecard']

# # fig, ax1 = plt.subplots()
# # ax2 = ax1.twinx()

# # line1=ax1.plot(np.arange(len(x)), y1, color='b',linestyle='--' , marker='o' , label='opencard')
# # line2=ax2.plot(np.arange(len(x)), y2, color='g',linestyle='--' , marker='^', label='usecard')


# # ax1.set_xticklabels(x)
# # ax1.set_xlabel('ages')
# # ax1.set_ylabel('opencard')
# # ax2.set_ylabel('usecard')

# # ax1.set_ylim(0,6)
# # ax2.set_ylim(0,6)

# # lines = line1 + line2
# # labels = [l.get_label() for l in lines]
# # plt.legend(lines,labels,loc=2)

# # plt.grid(False)

# # fig.tight_layout()
# # fig.savefig('Carduse.png' , dpi=1000)

# bar = pyecharts.Bar("Bar chart", "precipitation and evaporation one year")
# bar.use_theme("dark")
# bar.add("opencard", x, y1, mark_line=["average"], mark_point=["max", "min"])
# bar.add("usecard", x, y2, mark_line=["average"], mark_point=["max", "min"])
# bar.height = 500
# bar.width = 800
# bar

AttributeError: module 'pyecharts' has no attribute 'Bar'

In [ ]:
import matplotlib.pyplot as plt
import matplotlib
import matplotlib.font_manager as fm
import pyecharts

font_location = 'c:/Windows/Fonts/malgun.ttf'
font_name = fm.FontProperties(fname = font_location).get_name()
matplotlib.rc('font', family = font_name)